//
//  StudentInfo.swift
//  OnTheMap1
//
//  Created by ziming li on 2017-07-18.
//  Copyright © 2017 ziming li. All rights reserved.
//

import Foundation

struct StudentInfo {
    
    //  Description: an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
    var objectId: String?
    
    //  Description: an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id
    var uniqueKey: String?
    
    //  Description: the first name of the student which matches their Udacity profile first name
    var firstName: String?
    
    //  Description: the last name of the student which matches their Udacity profile last name
    var lastName: String?
    
    //  Description: the location string used for geocoding the student location
    var mapString: String?
    
    //  Description: the URL provided by the student
    var mediaURL: String?
    
    //  Description: the latitude of the student location (ranges from -90 to 90)
    var latitude: Double?
    
    //  Description: the longitude of the student location (ranges from -180 to 180)
    var longitude: Double?
    
    // MARK: Initialize Student Info into a Dictionary
    init(dictionary: [String: AnyObject]) {
        objectId = dictionary["objectId"] as? String
        uniqueKey = dictionary["uniqueKey"] as? String
        firstName = dictionary["firstName"] as? String
        lastName = dictionary["lastName"] as? String
        mapString = dictionary["mapString"] as? String
        mediaURL = dictionary["mediaURL"] as? String
        latitude = dictionary["latitude"] as? Double
        longitude = dictionary["longitude"] as? Double
    }
}
